FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY common_utils /app/common_utils
RUN pip install --no-cache-dir -e /app/common_utils

COPY indexer /app/indexer
RUN pip install --no-cache-dir -r  /app/indexer/requirements.txt

CMD ["python", "-m", "indexer/indexer"]
