FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY common_utils /app/common_utils
RUN pip install --no-cache-dir -e /app/common_utils

COPY IR /app/IR
RUN pip install --no-cache-dir -r  /app/IR/requirements.txt

RUN python -c "import nltk; nltk.download('punkt'); nltk.download('punkt_tab')"

EXPOSE 8000
CMD ["python", "-m", "uvicorn", "IR.app:app", "--host", "0.0.0.0", "--port", "8000"]
